List<Map> onboardpaintings = [
  {
    'image': 'lib/images/img6.jpeg',
    'name': '',
    'height': 100,
    'left': 7.0,
    'size': 40.0,
    'bottom': 8.0,
    'right': 5.0,
  },
  {
    'image': 'lib/images/carr.jpg',
    'name': 'Formula Student 101',
    'left': 80.0,
    'height': 100,
    'size': 20.0,
    'bottom': 8.0,
    'right': 0.0,
  },
  {
    'image': 'lib/images/img1.jpeg',
    'name': 'Formula Student 101',
    'left': 80.0,
    'height': 100,
    'size': 20.0,
    'bottom': 8.0,
    'right': 0.0,
  },
  {
    'image': 'lib/images/img2.jpeg',
    'name': 'Formula Student 101',
    'left': 80.0,
    'height': 100,
    'size': 20.0,
    'bottom': 8.0,
    'right': 0.0,
  },
  {
    'image': 'lib/images/img3.jpeg',
    'name': 'Formula Student 101',
    'left': 80.0,
    'height': 100,
    'size': 20.0,
    'bottom': 8.0,
    'right': 0.0,
  },

];
